### ISSUE TITLE
Can you add documentation to this lib?

### ISSUE THREAD

**Issue by sirvon** [billyshambrook/aiofirebase#4]
I'm having super problems with getting this setup...got it setup using asyncio but...

``` python
  5 firebase = aiofirebase.FirebaseHTTP("https://xxx.firebaseio.com/")
  6
  7 async def testor():
  8      return await firebase.get(path='test')
  9
 10
 11 loop = asyncio.get_event_loop()
 12 loop.run_until_complete(testor())
 13 loop.run_forever()
```

``` bash
Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8
Traceback (most recent call last):
  File "firebaseaioXNA.py", line 12, in <module>
    loop.run_until_complete(testor())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "firebaseaioXNA.py", line 8, in testor
    return await firebase.get(path='test')
  File "/usr/local/lib/python3.5/site-packages/aiofirebase/__init__.py", line 40, in get
    return await self._request(method='GET', path=path, params=params)
  File "/usr/local/lib/python3.5/site-packages/aiofirebase/__init__.py", line 92, in _request
    return await resp.json()
  File "/usr/local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 761, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x107528d30>
Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x1079252e8>
transport: <_SelectorSocketTransport fd=9>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 702, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x1079252e8>
transport: <_SelectorSocketTransport closing fd=9>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 702, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/sslproto.py", line 631, in _process_write_backlog
    self._transport.write(chunk)
File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 706, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 593, in _fatal_error
    self._force_close(exc)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 605, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 447, in call_soon
    handle = self._call_soon(callback, args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 456, in _call_soon
    self._check_closed()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 284, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by billyshambrook** [comment]
I have released 0.2.0 which fixes the above JSON error you were getting. Thanks for reporting it.

I will leave this issue open for adding better documentation.
