### ISSUE TITLE
watch for updates example

### ISSUE THREAD

**Issue by SirFernanders** [billyshambrook/aiofirebase#8]
Hello, is there any chance you could give a more clear example of the "watch for updates"?

**Comment by billyshambrook** [comment]
Hey @SirFernanders, could you expand on a user case that you would like to see?

**Comment by DiamondSwag** [comment]
Yes... Please provide a basic example with all code to function properly. Cannot seem to get this to work no matter what I do! 
`firebase = aiofirebase.FirebaseHTTP("https://mcp-passengers-67a37.firebaseio.com/")

async def Market(event, data):
    print('{} event received.'.format(event))

async def CheckMarket():
    return await firebase.stream(callback=Market, path='market')

loop = asyncio.get_event_loop()
loop.run_until_complete(CheckMarket())
loop.run_forever()`

Returns the following:

`Traceback (most recent call last):
  File "Test.py", line 16, in <module>
    loop.run_until_complete(CheckMarket())
  File "C:\Program Files (x86)\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "Test.py", line 13, in CheckMarket
    return await firebase.stream(callback=Market, path='market')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\aiofirebase\__init__.py", line 64, in stream
    await FirebaseHTTP._iterate_over_stream(resp.content.read(), callback)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\aiofirebase\__init__.py", line 69, in _iterate_over_stream
    async for msg in iterable:
TypeError: 'async for' requires an object with __aiter__ method, got generator
Unclosed client session`
